### ISSUE TITLE
ridley-4.1.2: gem conflict with berkshelf-3.2.2

### ISSUE THREAD

**Issue by haidangwa** [RiotGames/ridley#299]
test environment:
```
gem install test-kitchen
gem install berkshelf
gem install kitchen-vagrant
```
As of today, this installs test-kitchen 1.2.1, berkshelf 3.2.2, and kitchen-vagrant 0.15.0. As a result of the berkshelf install, it also installed ridley-4.1.2. However, this version of ridley has a gem dependency on retryable that conflicts with berkshelf Running test kitchen, I get the following error.

```
kitchen test
-----> Starting Kitchen (v1.2.1)
!!!!!! The `berkshelf' gem is missing and must be installed or cannot be properly activated. Run `gem install berkshelf` or add the following to your Gemfile if you are using Bundler: `gem 'berkshelf'`.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Could not load or activate Berkshelf (Unable to activate ridley-4.1.2, because retryable-1.3.6 conflicts with retryable (>= 2.0.0))
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Test kitchen works again when I uninstall ridley-4.1.2 and install ridley-4.1.1. Is this an issue with the berkshelf gem or ridley?

**Comment by reset** [comment]
@haidangwa this is a conflict with Berkshelf which hasn't had a new release to bump the required version of retryable.

It is not recommended to install Berkshelf via RubyGem to avoid gem dependency conflicts. Berkshelf is now part of the [ChefDK](https://downloads.chef.io/chef-dk/) which includes Test-Kitchen, Berkshelf, Chef, and other useful tools for Chef developers.

**Comment by benholtz** [comment]
Doesn't help those of us that cannot update our ChefDK and must rely on the gem installs, like those using Amazon Opsworks...

**Comment by reset** [comment]
@benholtz this is an unfortunate issue with Amazon Opsworks. If you're a user of their toolchain I would open an issue with them to explain that over a year ago the tooling shifted to this installation method and they need to get up to speed. It sucks but that's how it's gotta be :(.

**Comment by jmreicha** [comment]
I just ran across this (Opsworks/Berkshelf 3.2.0).  Has anybody found a workaround?

**Comment by jmreicha** [comment]
Never mind, uninstalling Ridley via `/opt/aws/opsworks/local/bin/gem uninstall ridley` and rerunning the install works.

I have a ticket open with AWS to see if I can get them to look at this though.

**Comment by mikebell90** [comment]
Same issue today for us on AWS opsworks sigh. Thanks jmreicha for the workaround
