### ISSUE TITLE
Upgrade of retryable dependency to new major version doesn't  seem to be a patch release

### ISSUE THREAD

**Issue by oleg-z** [RiotGames/ridley#302]
After upgrade of ridley gem to latest patch version was surprised to see that my app doesn't start anymore because of conflict of 'retryable' gem

Not sure is it actually a bug but it just doesn't seem right. Feel free to close it

**Comment by sethvargo** [comment]
https://github.com/RiotGames/ridley/issues/299

**Comment by reset** [comment]
@oleg-z yes, this is still a patch release. Bumping one of the versions of our dependencies doesn't change our public API in anyway, so we don't manipulate our major/minor version.

Download the latest ChefDK and you'll have all the things you need!

**Comment by oleg-z** [comment]
@reset I agree and that's why I mentioned that it's not actually a bug

In the same time such major gem dependency change causes problems if you build something on top of berkshelf without chefdk. 

Anyway thanks for quick response
